"""add order reservation expiry

Revision ID: 9340f762f032
Revises: 8764a361732a
Create Date: 2026-08-14 03:28:00.439440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9340f762f032'
down_revision: Union[str, Sequence[str], None] = '8764a361732a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('reserved_until', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'reserved_until')
    # ### end Alembic commands ###
